USE projecteDB;
insert into etakemons (name,tipo,puntos) VALUES ('rosa','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('hicham','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('oriol','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('jonatan','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('rodrigo','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('ivan','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('xavi','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('alberto','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('adria','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('paula','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('albert','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('marc','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('yuri','alumno','50');
insert into etakemons (name,tipo,puntos) VALUES ('juan','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('toni','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('lluis','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('francesca','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('david','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('antonia','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('santiago','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('pere','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('enrica','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('ana','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('sebastia','profesor','100');
insert into etakemons (name,tipo,puntos) VALUES ('alonso','director','200');

