USE projecteDB;
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('rosa','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('hicham','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('oriol','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('jonatan','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('rodrigo','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('ivan','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('xavi','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('alberto','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('adria','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('paula','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('albert','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('marc','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('yuri','alumno','50','alumno de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('juan','profesor','100','profesor de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('toni','profesor','100','profesor de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('lluis','profesor','100','profesor de DSA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('francesca','profesor','100','profesora de IOT');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('david','profesor','100','profesor de IOT');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('antonia','profesor','100','profesora de EA');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('santiago','profesor','100','profesor de TIQ');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('pere','profesor','100','profesor de TIQ');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('enrica','profesor','100','profesora de IX');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('ana','profesor','100','profesora de ADX');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('sebastia','profesor','100','profesor de PX');
insert into Etakemons (name,tipo,puntos,descripcion) VALUES ('alonso','director','200','director de la EETAC');