USE projecteDB;
insert into EtakemonsDescription (idetakemon,poder) VALUES ('1','ganas 20 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('2','ganas 10 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('3','ganas el doble de puntos');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('4','no pierdes puntos');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('5','solo pierdes la mitad de los puntos que deberias perder');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('6','ganas 10 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('7','ganas 10 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('8','ganas 5 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('9','ganas 5 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('10','ganas el doble de puntos');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('11','ganas 10 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('12','ganas 20 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('13','ganas 25 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('14','ganas el triple de puntos');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('15','ganas 50 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('16','ganas el doble de puntos');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('17','solo pierdes la mitad de los puntos que deberias perder');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('18','ganas 50 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('19','solo pierdes la mitad de los puntos que deberias perder');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('20','ganas el doble de puntos');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('21','no pierdes puntos');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('22','ganas el triple de puntos');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('23','ganas 50 puntos extra');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('24','no pierdes puntos');
insert into EtakemonsDescription (idetakemon,poder) VALUES ('25','ganas 200 puntos extra');

